import "./global.css";
import { Header } from "./header";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="fr" data-theme="light">
            <body>
                <Header />
                <div style={{ height: "calc(100vh - 32px)" }}>{children}</div>
            </body>
        </html>
    );
}
